package tietorakenne.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tietorakenne.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.04.08 11:11:19 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KalaTest {



  // Generated by ComTest BEGIN
  /** testLisaaKalaTiedot65 */
  @Test
  public void testLisaaKalaTiedot65() {    // Kala: 65
    Kala kala1 = new Kala(); 
    kala1.lisaaKalaTiedot(1); 
    assertEquals("From: Kala line: 68", 1, kala1.getKalaID()); 
    assertEquals("From: Kala line: 69", 1, kala1.getPyyntiID()); 
    Kala kala2 = new Kala(); 
    kala2.lisaaKalaTiedot(1); 
    assertEquals("From: Kala line: 73", 2, kala2.getKalaID()); 
    assertEquals("From: Kala line: 74", 1, kala2.getPyyntiID()); 
    Kala kala3 = new Kala(); 
    kala3.lisaaKalaTiedot(2); 
    assertEquals("From: Kala line: 78", 3, kala3.getKalaID()); 
    assertEquals("From: Kala line: 79", 2, kala3.getPyyntiID()); 
    Kala kala4 = new Kala(); 
    kala4.lisaaKalaTiedot(4); 
    assertEquals("From: Kala line: 83", 4, kala4.getKalaID()); 
    assertEquals("From: Kala line: 84", 4, kala4.getPyyntiID()); 
  } // Generated by ComTest END
}