package tietorakenne.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;

import java.util.Iterator;

import org.junit.*;
import tietorakenne.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.04.08 11:06:30 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class KalastajatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa38 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa38() throws SailoException {    // Kalastajat: 38
    Kalastajat kalastajat = new Kalastajat(); 
    Kalastaja testi1 = new Kalastaja(), testi2 = new Kalastaja(); 
    assertEquals("From: Kalastajat line: 42", 0, kalastajat.getLkm()); 
    kalastajat.lisaa(testi1); assertEquals("From: Kalastajat line: 43", 1, kalastajat.getLkm()); 
    kalastajat.lisaa(testi2); assertEquals("From: Kalastajat line: 44", 2, kalastajat.getLkm()); 
    kalastajat.lisaa(testi1); assertEquals("From: Kalastajat line: 45", 3, kalastajat.getLkm()); 
    Iterator<Kalastaja> it = kalastajat.iterator(); 
    assertEquals("From: Kalastajat line: 47", testi1, it.next()); 
    assertEquals("From: Kalastajat line: 48", testi2, it.next()); 
    assertEquals("From: Kalastajat line: 49", testi1, it.next()); 
    kalastajat.lisaa(testi1); assertEquals("From: Kalastajat line: 50", 4, kalastajat.getLkm()); 
    kalastajat.lisaa(testi1); assertEquals("From: Kalastajat line: 51", 5, kalastajat.getLkm()); 
  } // Generated by ComTest END
}