package tietorakenne.test;
// Generated by ComTest BEGIN
import java.util.*;
import java.io.File;
import static org.junit.Assert.*;
import org.junit.*;
import tietorakenne.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.04.26 15:19:15 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PyyntiTiedotTest {



  // Generated by ComTest BEGIN
  /** testAnnaPyyntiTiedot112 */
  @Test
  public void testAnnaPyyntiTiedot112() {    // PyyntiTiedot: 112
    PyyntiTiedot pyyntitiedot = new PyyntiTiedot(); 
    PyyntiTieto pyynti1 = new PyyntiTieto(), pyynti2 = new PyyntiTieto(), pyynti3 = new PyyntiTieto(); 
    pyynti1.luoarvot(1); 
    pyynti2.luoarvot(2); 
    pyynti1.luoarvot(1); 
    pyyntitiedot.lisaa(pyynti1); 
    pyyntitiedot.lisaa(pyynti2); 
    pyyntitiedot.lisaa(pyynti3); 
    List<PyyntiTieto> loytyneet; 
    loytyneet = pyyntitiedot.annaPyyntiTiedot(1); 
    assertEquals("From: PyyntiTiedot line: 125", 2, loytyneet.size()); 
    assertEquals("From: PyyntiTiedot line: 126", pyynti1, loytyneet.get(0)); 
    assertEquals("From: PyyntiTiedot line: 127", pyynti3, loytyneet.get(1)); 
    loytyneet = pyyntitiedot.annaPyyntiTiedot(2); 
    assertEquals("From: PyyntiTiedot line: 129", 1, loytyneet.size()); 
    assertEquals("From: PyyntiTiedot line: 130", pyynti2, loytyneet.get(0)); 
  } // Generated by ComTest END

}