package tietorakenne.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import tietorakenne.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2016.04.08 11:12:17 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PyyntiTietoTest {



  // Generated by ComTest BEGIN
  /** testLuoarvot43 */
  @Test
  public void testLuoarvot43() {    // PyyntiTieto: 43
    PyyntiTieto pyyntitieto1 = new PyyntiTieto(); 
    pyyntitieto1.luoarvot(1); 
    assertEquals("From: PyyntiTieto line: 46", 1, pyyntitieto1.getPyyntiID()); 
    assertEquals("From: PyyntiTieto line: 47", 1, pyyntitieto1.getKalastajaID()); 
    PyyntiTieto pyyntitieto2 = new PyyntiTieto(); 
    pyyntitieto2.luoarvot(1); 
    assertEquals("From: PyyntiTieto line: 51", 2, pyyntitieto2.getPyyntiID()); 
    assertEquals("From: PyyntiTieto line: 52", 1, pyyntitieto2.getKalastajaID()); 
    PyyntiTieto pyyntitieto3 = new PyyntiTieto(); 
    pyyntitieto3.luoarvot(2); 
    assertEquals("From: PyyntiTieto line: 56", 3, pyyntitieto3.getPyyntiID()); 
    assertEquals("From: PyyntiTieto line: 57", 2, pyyntitieto3.getKalastajaID()); 
    PyyntiTieto pyyntitieto4 = new PyyntiTieto(); 
    pyyntitieto4.luoarvot(4); 
    assertEquals("From: PyyntiTieto line: 61", 4, pyyntitieto4.getPyyntiID()); 
    assertEquals("From: PyyntiTieto line: 62", 4, pyyntitieto4.getKalastajaID()); 
  } // Generated by ComTest END
}